name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ github.sha }}

    - name: Authenticate with Google Cloud
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Get GKE cluster credentials
      uses: 'google-github-actions/get-gke-credentials@v1'
      with:
        cluster_name: 'hello-world-cluster'
        location: 'us-central1-c'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - name: Deploy to Kubernetes
      run: run: |
        # Use sed to replace the placeholder image tag in the deployment manifest with the new one
        sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ github.sha }}|' k8s/deployment.yaml

        # Apply the manifests to the cluster. This will create or update the resources.
        kubectl apply -f k8s/
